### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ShakedMev** [HaMosad1657/ChargedUp2023#56]
**Things to test+fix:**
- [ ] Test turret, and make it work with both encoder and limit switches
- [ ] Make arm work with encoder
- [ ] Make arm length work with both encoder and limit switches
- [ ] Make swerve work again :(
- [ ] Fix status leds problem

**Things to add:**
- [ ] Feedforward for arm angle
- [ ] Make commands take double suppliers instead of doubles
